amazon:
  access:
    key: AKIA24FGZII7CIKJRRXG
    secret-key: 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
  region: ap-south-1
  end-point:
    url: dynamodb.ap-south-1.amazonaws.com
server:
  port: 9001

